name: Build & deploy to GitHub Pages

# Run on every push to your main branch
on:
  push:
    branches:
      - main    # or replace with your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Setup Node.js (match your local version)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the static site into `dist/`
      - name: Build site
        run: npm run build

      # 5. Deploy `dist/` to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
