name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # ← or your default branch

# no special permissions needed here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Check out your code
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Install Node & deps, then build
      - name: Setup Node & Install
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Build Site
        run: npm run build

      # 3. Push `dist/` to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          # optional: clean before publish
          clean: true
