name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main    # or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read            # for checkout
      pages: write              # to publish
      id-token: write           # for actions/deploy-pages
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'    # match your local version

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build      # must output into dist/

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

      - name: Publish
        uses: actions/deploy-pages@v1
